// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0xNppIkeZsQCkONxVo4vDUj0wbGCL-nk',
    appId: '1:679037391262:web:16a73863d7a9a2e54a068f',
    messagingSenderId: '679037391262',
    projectId: 'ko4k-bff8a',
    authDomain: 'ko4k-bff8a.firebaseapp.com',
    databaseURL: 'https://ko4k-bff8a-default-rtdb.firebaseio.com',
    storageBucket: 'ko4k-bff8a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWX9UtTLHphnGwBs5fNaJ7-PXW4Gsq9lI',
    appId: '1:679037391262:android:a2dbab3ead9dc7c44a068f',
    messagingSenderId: '679037391262',
    projectId: 'ko4k-bff8a',
    databaseURL: 'https://ko4k-bff8a-default-rtdb.firebaseio.com',
    storageBucket: 'ko4k-bff8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCafK93rHIkUNfBdt81LOth-1tMy7j6vjo',
    appId: '1:679037391262:ios:9a58908a6b12e35f4a068f',
    messagingSenderId: '679037391262',
    projectId: 'ko4k-bff8a',
    databaseURL: 'https://ko4k-bff8a-default-rtdb.firebaseio.com',
    storageBucket: 'ko4k-bff8a.appspot.com',
    iosBundleId: 'com.example.ko4k',
  );
}
